<div id="article">
    <div id="article-title"> <h1>Parsare XML</h1> </div>
    <div id="article-author"> <h3>John Doe</h3></div>

    <div id="article-content">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non dolor at metus faucibus viverra. Quisque felis ante, aliquam sed interdum vel, semper in felis. Morbi vehicula urna eu augue gravida, eget pulvinar erat blandit. Sed vestibulum enim tortor, ut tincidunt nibh gravida ac. Vivamus a luctus purus. Nunc viverra hendrerit elementum. Vivamus vitae justo suscipit, interdum risus ac, varius diam. Praesent auctor arcu non erat consectetur, eget ultrices urna rhoncus. Etiam sagittis consequat neque at cursus.</p>
        <p>Pellentesque eu lectus est. Sed quis lacus nulla. Proin eget turpis est. Fusce in volutpat tellus. In eu lacus nec magna varius facilisis. Maecenas vel elit tempus, adipiscing metus eu, tincidunt lectus. Integer eget sem nec nulla volutpat auctor. Fusce pretium non urna varius iaculis. In eget cursus nisi, ut iaculis lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam quis vestibulum magna. Phasellus volutpat quam scelerisque diam elementum interdum. Quisque pulvinar nibh ac orci volutpat, ut dapibus massa faucibus.</p>
        <p>Etiam condimentum rutrum justo, sit amet tincidunt urna sodales ut. Suspendisse sollicitudin molestie ipsum, vel feugiat augue rutrum vel. Vestibulum consectetur lacus et tincidunt vulputate. Suspendisse commodo justo diam, a rhoncus dolor facilisis ac. Nulla non elit velit. Phasellus tincidunt, enim eu aliquet lobortis, diam felis congue felis, ac pharetra ante erat vitae dolor. Vestibulum a massa eget augue facilisis pulvinar ac rutrum ante. Sed lobortis volutpat risus, eget pulvinar nulla pharetra non. Suspendisse vitae mollis erat. Sed at porttitor dolor, at ultrices purus. Proin ullamcorper faucibus lacus ut vehicula. Nam lorem risus, mattis id blandit pulvinar, pulvinar a tellus. Nullam velit diam, faucibus vel dolor nec, facilisis ultricies arcu. Morbi pretium dolor a ipsum rhoncus vehicula.</p>
        <p>Sed pulvinar sapien a feugiat consectetur. Quisque malesuada mi quis erat aliquet consectetur. Aliquam quis eros eu enim porta euismod ac non justo. Maecenas congue, magna eget consectetur fringilla, quam mauris egestas turpis, vel lobortis neque tellus vitae magna. Vivamus eget sem felis. Ut eu magna lobortis, blandit odio in, venenatis eros. In non ligula imperdiet, sodales nulla eu, eleifend enim.</p>
        <p>Donec sagittis nisl ac nisl convallis, vitae pretium nisl auctor. Aenean scelerisque nisi non mauris pharetra, ut varius libero malesuada. Nunc a eros suscipit, blandit lacus a, molestie nibh. Aenean sapien lectus, tristique cursus nulla id, malesuada pharetra metus. Maecenas sit amet leo vehicula, tincidunt purus id, porttitor turpis. Curabitur interdum, leo in iaculis mattis, lorem metus aliquam libero, eget tristique sapien neque laoreet velit. Donec eu ipsum justo. Proin metus eros, hendrerit vel sapien sed, iaculis euismod mauris. Duis ligula massa, hendrerit id bibendum eu, convallis quis diam. Donec interdum leo ligula, vitae aliquet ligula cursus vel. Praesent scelerisque iaculis volutpat. Suspendisse eros eros, hendrerit sollicitudin magna vitae, molestie placerat enim. Cras eros odio, sagittis at leo ac, adipiscing malesuada ipsum. Praesent id tincidunt arcu, sed malesuada libero.</p>
    </div>
</div>

<?php require_once("sidebar.php"); ?>
<?php require_once("comments.php"); ?>
